'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WpfApp2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property ariba() As String
            Get
                Return ResourceManager.GetString("ariba", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TABLE_QUALIFIER,TABLE_OWNER,TABLE_NAME,TABLE_TYPE,REMARKS
        '''concept_accounts_cost_of_sales_reconciliation_co1
        '''concept_accounts_draft_invoices_co1
        '''concept_accounts_duplicate_references_co1
        '''concept_accounts_inactive_clients_co1
        '''concept_accounts_job_accruals_co1
        '''concept_accounts_job_billings_profit_co1
        '''concept_accounts_job_draft_invoices_co1
        '''concept_accounts_job_quotes_co1
        '''concept_accounts_media_accrual_co1
        '''concept_accounts_media_asbof_billings_co1
        '''concept_accounts_media_postings_co1
        '''concept_accounts [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property concept_accounts() As String
            Get
                Return ResourceManager.GetString("concept_accounts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to concept_audit_SIXREC_COS_co1
        '''concept_audit_SIXREC_SALES_co1
        '''concept_audit_contact_name_audit_co1
        '''concept_audit_general_audit_co1
        '''concept_audit_media_booking_audit_co1
        '''concept_audit_recent_email_exception_errors_co1
        '''concept_audit_report_auto_run_audit_co1
        '''concept_audit_system_audit_co1
        '''concept_audit_timesheets_locked_co1
        '''concept_audit_web_timesheet_co1
        '''concept_audit_web_timesheet_detail_co1.
        '''</summary>
        Friend ReadOnly Property concept_audit() As String
            Get
                Return ResourceManager.GetString("concept_audit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to concept_database_activities_co1
        '''concept_database_activity_rates_co1
        '''concept_database_ad_copy_fresh_jobs_co1
        '''concept_database_client_additional_charges_co1
        '''concept_database_client_billing_job_and_media_terms_co1
        '''concept_database_client_billing_media_terms_co1
        '''concept_database_client_cost_centre_rates_co1
        '''concept_database_client_credit_terms_co1
        '''concept_database_client_email_details_co1
        '''concept_database_client_employee_time_rates_co1
        '''concept_database_client_media_contract_terms_co1
        '''concept_database [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property concept_database() As String
            Get
                Return ResourceManager.GetString("concept_database", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TABLE_QUALIFIER,TABLE_OWNER,TABLE_NAME,TABLE_TYPE,REMARKS
        '''concept_mgmt_aged_creditors_detail_co1
        '''concept_mgmt_aged_debtors_detail_co1
        '''concept_mgmt_client_balances_co1
        '''concept_mgmt_income_analysis_co1
        '''concept_mgmt_job_activity_budget_vs_actual_co1
        '''concept_mgmt_job_bag_detail_co1
        '''concept_mgmt_job_bag_summary_co1
        '''concept_mgmt_job_budget_audit_co1
        '''concept_mgmt_job_master_detail_co1
        '''concept_mgmt_job_master_detail_single_co1
        '''concept_mgmt_job_schedule_co1
        '''concept_mgmt_job_summary_co1
        '''concept_mgmt_job_ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property concept_mgmt() As String
            Get
                Return ResourceManager.GetString("concept_mgmt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TABLE_QUALIFIER,TABLE_OWNER,TABLE_NAME,TABLE_TYPE,REMARKS
        '''concept_time_analysis~1
        '''concept_time_daily_time_analysis~1
        '''concept_time_days_time_entered~1
        '''concept_time_hours_required_by_day~1
        '''concept_time_hours_required_last_365_days~1
        '''concept_time_hours_worked_by_employee_by_day~1
        '''concept_time_information~1
        '''concept_time_missing_timsheets_daily_co1
        '''concept_time_missing_timsheets_weekly_co1
        '''concept_time_pg1~1
        '''concept_time_pg2~1
        '''concept_time_pg3~1
        '''concept_time_pg~1
        '''concept_time_pre_update_report_co1        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property concept_time() As String
            Get
                Return ResourceManager.GetString("concept_time", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to concept_xx_jc_cst_jpa_wip_diffs_co1
        '''concept_xx_jc_cst_trn_order_diffs_co1
        '''concept_xx_jc_jcjpa_clmst_nlmst_wip_bal_co1
        '''concept_xx_jc_jcjpa_clmst_wip_diffs_co1
        '''concept_xx_jc_jpa_totals~co1
        '''concept_xx_jc_missing_clmst_from_jccst_co1
        '''concept_xx_jc_missing_clmst_from_jctrn_co1
        '''concept_xx_jc_missing_jccst_from_jctrn_co1
        '''concept_xx_jc_missing_jcmst_from_jccst_co1
        '''concept_xx_jc_missing_jcref_from_jctrn_co1
        '''concept_xx_jc_missing_jctrn_from_jcjpa_co1
        '''concept_xx_jc_missing_jctrn_from_jcref_co1
        '''concept_xx_j [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property concept_xx() As String
            Get
                Return ResourceManager.GetString("concept_xx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 142399,SSMENUX,,Sales Ledger,M,MSLMENU,,
        '''142400,SSMENUX,MSLMENU,Account Details and Enquiry,P,PSLPENQ,,
        '''142401,SSMENUX,MSLMENU,Journal Postings,P,PSLPJNL,,
        '''142402,SSMENUX,MSLMENU,Cash Postings,P,PSLPCSH  E,,
        '''142403,SSMENUX,MSLMENU,Client Terms,P,PSLTERMS.exe,ENV=&lt;ENV&gt; CONO=&lt;CO&gt;,^
        '''142404,SSMENUX,MSLMENU,Reports,M,MSLMENUR,,
        '''142405,SSMENUX,MSLMENUR,Aged Debt Analysis,P,PSLPADA,,
        '''142406,SSMENUX,MSLMENUR,Statement Print,P,PSLPSTM,,
        '''142407,SSMENUX,MSLMENUR,Credit Exposure,P,PSLPCER,,
        '''142408,SSMENUX,,Pur [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DummySSMENUS() As String
            Get
                Return ResourceManager.GetString("DummySSMENUS", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
